### ISSUE TITLE
CLI to create-filecoin-app

### ISSUE THREAD

**Issue by xBalbinus** [FIL-Builders/fil-frame#12]

**Comment by xBalbinus** [comment]
The CLI should preferrably have flags for which 'kind' of template we want to generate, and proceed to put in hooks or not for each feature case.

**Comment by lordshashank** [comment]
Yeah so my point here is we can develop a universal scaffold type solution with all the features we have regarding fvm, now when users would be using cli to create there app they can choose among them like we do with `npx create next app` and get options to choose among typescript project, eslint ,etc. 
This way we can have options like storacha, deal client, deal client with raas, akave, lighthouse, etc and builders would get the features or all the features if they want.

**Comment by temi0x** [comment]
What flags should we have from the onset @xBalbinus?
The implementation I have currently has just a simple command (create-filecoin-app init my-app)

**Comment by xBalbinus** [comment]
https://docs.google.com/document/d/1KE7EGbbSIOrRXQRisc1C4kHOtD62BOPp3s1B8HxCfIA/edit?tab=t.0#heading=h.lbznbjhfs6j1

@temi0x prepare for the following type of extension in your code for now; but for the onset you can feel free to just have one simple command. Effectively, it should end up looking something like:

npx create-filecoin-app -<flag_name> feature-branch-name

**Comment by temi0x** [comment]
@xBalbinus I opened a PR that fixes this: https://github.com/FIL-Builders/fil-frame/pull/38

**Comment by xBalbinus** [comment]
https://github.com/FIL-Builders/create-fil-frame
