### ISSUE TITLE
Storacha / Akave integration

### ISSUE THREAD

**Issue by xBalbinus** [FIL-Builders/fil-frame#21]
Integrate on a separate branch with Storacha / Akave for file-storage example... an initial idea is with NFTs?

Implement basic NFT contract containing URI field
Allow user to upload large files onto Storacha / Akave, using the output as URI
Testing complete workflow in calibration.
Proper ABI/artifact generation to be used in frontend.

**Comment by trruckerfling** [comment]
for [storacha](https://github.com/storacha/w3up) and akave (need to find out more here but they are putting a bounty for bangkok, so definitely something available), I see them as pluggable options for storage onramps within the starter kit. will let you decide on use case

**Comment by nijoe1** [comment]
We can have a different PR for lighthouse integration.

Lighthouse supports natively encryption which is kind of cool !

**Comment by xBalbinus** [comment]
For storacha, does this require a credit card on testnet still?

**Comment by nijoe1** [comment]
> For storacha, does this require a credit card on testnet still?

Yes Storacha is not depending on a blockchain.

Users/devs should include their credit card but they can have first GBs for free

**Comment by nijoe1** [comment]
@xBalbinus Created the Storacha-nfts branch here https://github.com/FIL-Builders/fil-frame/tree/storacha-nfts

If this satisfies the issue let's close it!!!
